# Supabase Configuration

[api]
enabled = true
port = 54321
schemas = ["public", "auth", "storage"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000/**"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.sms]
enable_signup = true
enable_confirmations = true
template = "Your code is {{ .Code }}"

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"

[functions]
# No functions configured yet

[storage]
enabled = true

[storage.buckets.tours]
public = true
file_size_limit = "50MB"
allowed_mime_types = ["image/jpeg", "image/png", "image/webp", "application/pdf"]

[storage.buckets.operators]
public = true
file_size_limit = "10MB"
allowed_mime_types = ["image/jpeg", "image/png", "image/svg+xml"]

[storage.buckets.widgets]
public = true
file_size_limit = "5MB"
allowed_mime_types = ["text/javascript", "text/css", "application/json"]